---
title: "Getting Started"
author: "Riley Leff"
date: "3/26/2020"
output: html_document
---

```{r}
library(Rcpp)
sourceCpp("/Users/leff701/Documents/dev/ezSperry-beta/SperryModelBase.cpp")
source("/Users/leff701/Documents/dev/ezSperry-beta/classes.R")
```

```{r}
model1 = new_sperry_model("/Users/leff701/Documents/dev/ezSperry-beta/")
run_sperry(model1)
```
```{r}
library(tidyverse)
bci_temp = read.csv("/Users/leff701/Documents/data/bci_air_temp_91_to_20.csv")
bci_solar = read.csv("/Users/leff701/Documents/data/bci_solar_2010to20.csv")
```



```{r}
# found a bug? shoot Riley a message and you'll increase your score on the leaderboard!
# Try it here: 

score_log = ez_leaderboard() # prints leaderboard
score_log # prints scoring log 

# Scoring: 
    # 3 points -- found error in code base
    # 2 points -- found error in docs OR good idea for code base
    # 1 point -- good idea for docs

# leaderboard updates in real-time.....but won't work if you're not connected to internet
# just run the function again to get the latest scoreboard.  no need to re-source or re-download.
# if function fails, try manually installing the packages "httr" and "stringr"
```






