root_wb = "@Parameters@weibull[1,2]"
root_wc = "@Parameters@weibull[2,2]"
root_p_r_ksat = "@Parameters@weibull[3,2]"
stem_wb = "@Parameters@weibull[1,3]"
stem_wc = "@Parameters@weibull[2,3]"
stem_p_r_ksat = "@Parameters@weibull[3,3]"
leaf_wb = "@Parameters@weibull[1,4]"
leaf_wc = "@Parameters@weibull[2,4]"
leaf_p_r_ksat = "@Parameters@weibull[3,4]"
plant_kmax = "@Parameters@Plant@plant_kmax"
height = "@Parameters@Plant@height"
la_to_ba = "@Parameters@Plant@la_to_ba"
leaf_width = "@Parameters@Plant@leaf_width"
avg_p_rhizo_r = "@Parameters@Plant@avg_p_rhizo_r"
root_aspect_r = "@Parameters@Plant@root_aspect_r"
root_beta = "@Parameters@Plant@root_beta"
latitude = "@Parameters@Stand@latitude"
longitude = "@Parameters@Stand@longitude"
slope_inc = "@Parameters@Stand@slope_inc"
slope_aspect = "@Parameters@Stand@slope_aspect"
leaf_angle_p = "@Parameters@Stand@leaf_angle_p"
canopy_lai = "@Parameters@Stand@canopy_lai"
height_above_soil = "@Parameters@Stand@height_above_soil"
site_elevation = "@Parameters@Stand@site_elevation"
solar_noon_corr = "@Parameters@Stand@solar_noon_corr"
ba_to_ga = "@Parameters@Stand@ba_to_ga"
field_cap_frac = "@Parameters@Soil@field_cap_frac"
init_p_field_cap = "@Parameters@Soil@init_p_field_cap"
rock_fraction = "@Parameters@Soil@rock_fraction"
soil_abs = "@Parameters@Soil@soil_abs"
tlai_to_plai = "@Parameters@Soil@tlai_to_plai"
p_inc = "@Parameters@Soil@p_inc"
atm_co2_pa = "@Parameters@Photosynthesis@atm_co2_pa"
atm_co2_ppm = "@Parameters@Photosynthesis@atm_co2_ppm"
quantum_yield_e_t = "@Parameters@Photosynthesis@quantum_yield_e_t"
vmax = "@Parameters@Photosynthesis@vmax"
jmax = "@Parameters@Photosynthesis@jmax"
kc = "@Parameters@Photosynthesis@kc"
ko = "@Parameters@Photosynthesis@ko"
comp_point = "@Parameters@Photosynthesis@comp_point"
theta = "@Parameters@Photosynthesis@theta"
ha_vmax = "@Parameters@Photosynthesis@ha_vmax"
hd_vmax = "@Parameters@Photosynthesis@hd_vmax"
sv_vmax = "@Parameters@Photosynthesis@sv_vmax"
curv_light_resp = "@Parameters@Photosynthesis@curv_light_resp"
light_comp = "@Parameters@Photosynthesis@light_comp"
ha_jmax = "@Parameters@Photosynthesis@ha_jmax"
hd_jmax = "@Parameters@Photosynthesis@hd_jmax"
sv_jmax = "@Parameters@Photosynthesis@sv_jmax"
sky_emiss = "@Parameters@Atmospheric@sky_emiss"
atm_trans = "@Parameters@Atmospheric@atm_trans"
o2_mol_frac = "@Parameters@Atmospheric@o2_mol_frac"
gw_p = "@Parameters@Options@gw_p"
gw_d = "@Parameters@Options@gw_d"
gw = "@Parameters@Options@gw"
early_kill_plc = "@Parameters@Options@early_kill_plc"
soil_redist = "@Parameters@Options@soil_redist"
soil_evap = "@Parameters@Options@soil_evap"
refilling = "@Parameters@Options@refilling"
rain = "@Parameters@Options@rain"
use_gs_data = "@Parameters@Options@use_gs_data"
weibin_mode = "@Parameters@Options@weibin_mode"
alex_mode = "@Parameters@Options@alex_mode"
depth_override = "@Parameters@Options@depth_override"
radius_override = "@Parameters@Options@radius_override"
soil_verbose = "@Parameters@Options@soil_verbose"
tag = "@Parameters@Options@tag"
id = "@Parameters@Options@id"
vg_n_1 = "@Parameters@soil_layers$vg_n[1]"
vg_a_1 = "@Parameters@soil_layers$vg_n[1]"
theta_sat_1 = "@Parameters@soil_layers$theta_sat[1]"
vg_n_2 = "@Parameters@soil_layers$vg_n[2]"
vg_a_2 = "@Parameters@soil_layers$vg_n[2]"
theta_sat_2 = "@Parameters@soil_layers$theta_sat[2]"
vg_n_3 = "@Parameters@soil_layers$vg_n[3]"
vg_a_3 = "@Parameters@soil_layers$vg_n[3]"
theta_sat_3 = "@Parameters@soil_layers$theta_sat[3]"
vg_n_4 = "@Parameters@soil_layers$vg_n[4]"
vg_a_4 = "@Parameters@soil_layers$vg_n[4]"
theta_sat_4 = "@Parameters@soil_layers$theta_sat[4]"
vg_n_5 = "@Parameters@soil_layers$vg_n[5]"
vg_a_5 = "@Parameters@soil_layers$vg_n[5]"
theta_sat_5 = "@Parameters@soil_layers$theta_sat[5]"
soil_layers = "@Parameters@soil_layers"
data = "@data"