# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runit2 <- function(modelobj, jmax_vary = 0L, vmax_vary = 0L, lai_vary = 0L, swc_vary = 0L, dep_vary = 0L, rad_vary = 0L, read_n_layers = 5L, nametag = "spemo", riyc = 0L, rinr = 0L) {
    .Call(`_ezsperry_runit2`, modelobj, jmax_vary, vmax_vary, lai_vary, swc_vary, dep_vary, rad_vary, read_n_layers, nametag, riyc, rinr)
}

